from claude import Claude
from functions.top_one import top_one

sample = [
    {
        "title": "Large-scale on-chip integration of gate-voltage addressable hybrid superconductor-semiconductor quantum wells field effect nano-switch arrays ",
        "summary": "Stable, reproducible, scalable, addressable, and controllable hybrid superconductor-semiconductor (S-Sm) junctions and switches are key circuit elements and building blocks of gate-based quantum processors. The electrostatic field effect produced by the split gate voltages facilitates the realisation of nano-switches that can control the conductance or current in the hybrid S-Sm circuits based on 2D semiconducting electron systems. Here, we experimentally demonstrate a novel realisation of large-scale scalable, and gate voltage controllable hybrid field effect quantum chips. Each chip contains arrays of split gate field effect hybrid junctions, that work as conductance switches, and are made from In0.75Ga0.25As quantum wells integrated with Nb superconducting electronic circuits. Each hybrid junction in the chip can be controlled and addressed through its corresponding source-drain and two global split gate contact pads that allow switching between their (super)conducting and insulating states. We fabricate a total of 18 quantum chips with 144 field effect hybrid Nb- In0.75Ga0.25As 2DEG-Nb quantum wires and investigate the electrical response, switching voltage (on/off) statistics, quantum yield, and reproducibility of several devices at cryogenic temperatures. The proposed integrated quantum device architecture allows control of individual junctions in a large array on a chip useful for the development of emerging cryogenic nanoelectronics circuits and systems for their potential applications in fault-tolerant quantum technologies.",
        "url": "https://arxiv.org/abs/2307.04355",
        "publishDate": "10 July, 2023"
    },
    {
        "title": "Higgs amplitude mode in ballistic superconducting hybrid junctions",
        "summary": " In superconductors (SC), the Higgs amplitude mode is a coherent oscillation of the order parameter typically generated by THz laser irradiation. In this paper we propose to probe the Higgs mode using electronic transport in ballistic superconducting hybrid devices. We first confirm the existence of a non-zero amplitude mode in the clean case using the Keldysh-Eilenberger formalism. We then investigate two different geometries, respectively a normal-insulating-superconductor (NIS) tunnel junction and a NSN junction with transparent interfaces, the superconductor being irradiated in both situations. In the NIS case, the Higgs manifests itself in the second-order AC current response which is resonant at the Higgs frequency. In the NSN case, the DC differential conductance allows to probe the gaps generated by the Higgs mode in the Floquet spectrum",
        "url": "https://arxiv.org/abs/2307.06019",
        "publishDate": "12 July, 2023"
    },
    {
        "title": "A Transformer-based Approach for Arabic Offline Handwritten Text Recognition ",
        "summary": "Handwriting recognition is a challenging and critical problem in the fields of pattern recognition and machine learning, with applications spanning a wide range of domains. In this paper, we focus on the specific issue of recognizing offline Arabic handwritten text. Existing approaches typically utilize a combination of convolutional neural networks for image feature extraction and recurrent neural networks for temporal modeling, with connectionist temporal classification used for text generation. However, these methods suffer from a lack of parallelization due to the sequential nature of recurrent neural networks. Furthermore, these models cannot account for linguistic rules, necessitating the use of an external language model in the post-processing stage to boost accuracy. To overcome these issues, we introduce two alternative architectures, namely the Transformer Transducer and the standard sequence-to-sequence Transformer, and compare their performance in terms of accuracy and speed. Our approach can model language dependencies and relies only on the attention mechanism, thereby making it more parallelizable and less complex. We employ pre-trained Transformers for both image understanding and language modeling. Our evaluation on the Arabic KHATT dataset demonstrates that our proposed method outperforms the current state-of-the-art approaches for recognizing offline Arabic handwritten text.",
        "url": "https://arxiv.org/abs/2307.15045",
        "publishDate": "27 July, 2023"
    },
]
query = "I want to learn about superconductors"
top_one(sample, query)
